# Generated by Django 5.1.2 on 2024-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='مشخصات')),
                ('nezam', models.SlugField(max_length=100, unique=True, verbose_name='نظام پزشکی')),
                ('mobile', models.CharField(max_length=200, null=True, verbose_name='موبایل')),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'my test',
            },
        ),
    ]
