# Generated by Django 5.1.2 on 2024-12-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_physician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.IntegerField(default=1)),
                ('image', models.TextField(null=True)),
                ('params', models.TextField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageable_type', models.CharField(max_length=255)),
                ('imageable_id', models.BigIntegerField()),
                ('src', models.TextField()),
                ('alt', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'images',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_catalog_id', models.BigIntegerField(null=True)),
                ('product_code', models.CharField(max_length=255, null=True)),
                ('price', models.BigIntegerField(default=0)),
                ('pre_price', models.BigIntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('discount_expire_at', models.DateTimeField(null=True)),
                ('qty', models.BigIntegerField(default=0)),
                ('color', models.CharField(max_length=255, null=True)),
                ('color_name', models.CharField(max_length=255, null=True)),
                ('color_name_en', models.CharField(max_length=255, null=True)),
                ('warranty', models.CharField(max_length=255, null=True)),
                ('wight', models.IntegerField(default=0)),
                ('params', models.TextField()),
                ('good_id', models.BigIntegerField(null=True)),
                ('goodsCode', models.CharField(max_length=255, null=True)),
                ('typeCode', models.IntegerField(null=True)),
                ('tafsiliID', models.IntegerField(null=True)),
                ('good_info', models.TextField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('code', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('en_title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('brand_id', models.BigIntegerField(default=0)),
                ('product_attribute', models.TextField(null=True)),
                ('type', models.IntegerField(default=0)),
                ('is_active', models.IntegerField(default=1)),
                ('is_special', models.IntegerField(default=0)),
                ('out_of_sell', models.IntegerField(default=0)),
                ('is_coming_soon', models.IntegerField(default=1)),
                ('image', models.TextField(null=True)),
                ('params', models.TextField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'product_catalogs',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('description', models.TextField(null=True)),
                ('type', models.IntegerField(default=1)),
                ('sob_type', models.IntegerField(default=1)),
                ('image_icon', models.TextField(null=True)),
                ('image_menu', models.TextField(null=True)),
                ('image_app', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('show_type', models.CharField(max_length=255, null=True)),
                ('show_on_mobile', models.IntegerField(default=0)),
                ('page_id', models.IntegerField(null=True)),
                ('position', models.IntegerField(null=True)),
                ('active', models.IntegerField(default=1)),
                ('params', models.TextField(null=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='categories', to='shop_api.productcatalogcategory', verbose_name='دسته')),
            ],
            options={
                'db_table': 'product_catalog_categories',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogCategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group_id', models.IntegerField()),
                ('product_catalog_category_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.IntegerField(default=1)),
                ('image', models.TextField(null=True)),
                ('params', models.TextField()),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogCategoryAttributeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('image', models.TextField(null=True)),
                ('params', models.TextField(null=True)),
                ('position', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'attribute_groups',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogCategoryAttributeProductValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_catalogs_id', models.BigIntegerField()),
                ('attribute_id', models.BigIntegerField()),
                ('value_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'attribute_value_products',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogCategoryAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_group_id', models.IntegerField()),
                ('attribute_id', models.BigIntegerField()),
                ('value', models.TextField()),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'attribute_values',
            },
        ),
        migrations.CreateModel(
            name='ProductCatalogCategoryRels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category', to='shop_api.productcatalogcategory')),
                ('product_catalog', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_catalog', to='shop_api.productcatalog')),
            ],
            options={
                'db_table': 'product_catalog_category_rels',
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='عنوان')),
                ('val', models.TextField(null=True, verbose_name='مقدار')),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sob_settings',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('src', models.TextField(null=True)),
                ('type', models.IntegerField(default=0)),
                ('position', models.IntegerField(default=0)),
                ('sort', models.IntegerField(default=0)),
                ('params', models.TextField()),
                ('cats', models.TextField(null=True)),
                ('image_mobile', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('active', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sliders',
            },
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField()),
                ('meta_key', models.CharField(max_length=255, verbose_name='عنوان')),
                ('meta_value', models.TextField(null=True, verbose_name='مقدار')),
                ('create_at', models.DateTimeField(null=True)),
                ('update_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'sob_user_meta',
            },
        ),
        migrations.DeleteModel(
            name='Physician',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
    ]
